#ifndef CONFIG_PORTAL_HTML_H
#define CONFIG_PORTAL_HTML_H

// Phase 4 T030: Configuration portal HTML page (split to avoid raw string issues)
static const char CONFIG_PORTAL_HTML[] = 
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32 Audio Setup</title>"
"<style>"
"body{font-family:Arial,sans-serif;max-width:480px;margin:20px auto;padding:0 20px;background:#f5f5f5}"
".card{background:white;border-radius:8px;padding:20px;box-shadow:0 2px 4px rgba(0,0,0,0.1);margin-bottom:20px}"
"h1{color:#333;font-size:24px;margin:0 0 10px}"
".subtitle{color:#666;font-size:14px;margin-bottom:20px}"
"label{display:block;margin:15px 0 5px;font-weight:600;color:#333}"
"input,select{width:100%;padding:10px;border:1px solid #ddd;border-radius:4px;font-size:16px;box-sizing:border-box}"
"button{width:100%;padding:12px;background:#007bff;color:white;border:none;border-radius:4px;font-size:16px;font-weight:600;cursor:pointer;margin-top:20px}"
"button:hover{background:#0056b3}"
".status{padding:10px;border-radius:4px;margin-top:15px;display:none}"
".success{background:#d4edda;color:#155724}"
".error{background:#f8d7da;color:#721c24}"
"#networks{margin-top:10px}"
".network{padding:10px;cursor:pointer;border-bottom:1px solid #eee}"
".network:hover{background:#f8f9fa}"
".loading{text-align:center;padding:20px;color:#666}"
"</style></head><body>"
"<div class='card'>"
"<h1>ESP32 Audio Streamer</h1>"
"<div class='subtitle'>WiFi Configuration</div>"
"<form id='configForm'>"
"<label>WiFi Network</label>"
"<input type='text' id='ssid' name='ssid' placeholder='Select or enter SSID' required>"
"<div id='networks' style='display:none'></div>"
"<button type='button' onclick='scanNetworks()' style='background:#6c757d;margin-top:10px'>Scan Networks</button>"
"<label>WiFi Password</label>"
"<input type='password' id='password' name='password' placeholder='Enter password'>"
"<label>Sample Rate</label>"
"<select id='sample_rate' name='sample_rate'>"
"<option value='44100'>44.1 kHz</option>"
"<option value='48000' selected>48 kHz</option>"
"<option value='96000'>96 kHz</option>"
"</select>"
"<label>Device Name (mDNS hostname)</label>"
"<input type='text' id='device_name' name='device_name' value='esp32-audio-stream' placeholder='esp32-audio-stream'>"
"<button type='submit'>Save & Connect</button>"
"</form>"
"<div id='status' class='status'></div>"
"</div>"
"<script>"
"function scanNetworks(){"
"document.getElementById('networks').innerHTML='<div class=\"loading\">Scanning...</div>';"
"document.getElementById('networks').style.display='block';"
"fetch('/wifi/scan')"
".then(r=>r.json())"
".then(data=>{"
"let html='';"
"data.networks.forEach(n=>{"
"html+='<div class=\"network\" onclick=\"selectNetwork(\\''+n.ssid+'\\',\\''+n.auth+'\\')\">'+"
"n.ssid+' ('+n.rssi+'dBm) '+(n.auth!=='open'?'🔒':'')+'</div>';"
"});"
"document.getElementById('networks').innerHTML=html||'<div class=\"loading\">No networks found</div>';"
"})"
".catch(()=>{"
"document.getElementById('networks').innerHTML='<div class=\"loading\">Scan failed</div>';"
"});"
"}"
"function selectNetwork(ssid,auth){"
"document.getElementById('ssid').value=ssid;"
"document.getElementById('password').disabled=(auth==='open');"
"document.getElementById('networks').style.display='none';"
"}"
"document.getElementById('configForm').onsubmit=function(e){"
"e.preventDefault();"
"let status=document.getElementById('status');"
"status.className='status';"
"status.textContent='Saving configuration...';"
"status.style.display='block';"
"let formData=new FormData(this);"
"let params=new URLSearchParams(formData).toString();"
"fetch('/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params})"
".then(r=>r.json())"
".then(data=>{"
"status.className='status success';"
"status.textContent=data.message||'Configuration saved! Device restarting...';"
"setTimeout(()=>{location.reload()},3000);"
"})"
".catch(err=>{"
"status.className='status error';"
"status.textContent='Failed to save configuration. Please try again.';"
"});"
"};"
"fetch('/config')"
".then(r=>r.json())"
".then(data=>{"
"if(data.ssid)document.getElementById('ssid').value=data.ssid;"
"if(data.sample_rate)document.getElementById('sample_rate').value=data.sample_rate;"
"if(data.device_name)document.getElementById('device_name').value=data.device_name;"
"});"
"</script>"
"</body></html>";

#endif // CONFIG_PORTAL_HTML_H
