#include "pcm1808_driver.h"
#include "../system/error_handler.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "pcm1808";

// PCM1808 power-up timing requirements (from datasheet)
constexpr uint32_t POWER_SETTLING_MS = 500;  // VA/VD settling time
constexpr uint32_t RST_MIN_CYCLES = 4;       // Minimum RST LOW cycles (SCKI)

bool PCM1808Driver::init()
{
    ESP_LOGI(TAG, "Initializing PCM1808 ADC");
    
    // PCM1808 power-up sequence (from datasheet):
    // 1. Apply VA (analog 5V) first
    // 2. Apply VD (digital 3.3V) 
    // 3. Wait 500ms for power supplies to settle
    // 4. Apply system clock (SCKI)
    // 5. Assert RST LOW for ≥4 SCKI cycles
    // 6. De-assert RST HIGH to start operation
    
    // Note: In this hardware configuration, VA and VD are always-on supplies
    // and FMT0/FMT1/MD0/MD1 are hardwired (LOW = I²S slave mode).
    // RST pin is either hardwired HIGH or controlled via GPIO (TBD).
    // SCKI is generated by I²S master (GPIO9 on ESP32-S3).
    
    // Wait for power supply settling
    ESP_LOGI(TAG, "Waiting %d ms for power supply settling", POWER_SETTLING_MS);
    vTaskDelay(pdMS_TO_TICKS(POWER_SETTLING_MS));
    
    // If RST pin is GPIO-controlled, handle reset sequence here:
    // gpio_set_level(RST_GPIO, 0);  // Assert RST LOW
    // vTaskDelay(pdMS_TO_TICKS(1)); // Wait >4 SCKI cycles (~0.3μs at 12MHz)
    // gpio_set_level(RST_GPIO, 1);  // De-assert RST HIGH
    
    // For now, assume RST is hardwired HIGH or has external RC reset circuit
    
    ESP_LOGI(TAG, "PCM1808 initialization complete");
    ErrorHandler::log_info("PCM1808", "ADC ready for I²S data capture");
    
    return true;
}

bool PCM1808Driver::validate_clock(uint32_t sample_rate)
{
    // PCM1808 requires SCKI at 256fs, 384fs, or 512fs
    // I²S master provides 256fs on GPIO0 (MCLK)
    
    uint32_t expected_scki_hz = sample_rate * 256;
    
    // Validate sample rate is supported
    if (sample_rate != 44100 && sample_rate != 48000 && sample_rate != 96000) {
        ErrorHandler::log_error(ErrorType::I2S_ERROR, 
                                "Unsupported sample rate for PCM1808");
        return false;
    }
    
    ESP_LOGI(TAG, "Clock validated: %d Hz sample rate, %d Hz SCKI", 
             sample_rate, expected_scki_hz);
    
    return true;
}

void PCM1808Driver::deinit()
{
    // If RST is GPIO-controlled, assert RST LOW to disable ADC
    // gpio_set_level(RST_GPIO, 0);
    
    ESP_LOGI(TAG, "PCM1808 deinitialized");
}
